spring.application.name=springboot-web-app-1
spring.datasource.url=jdbc:mysql://venuguides.czqae8k0orr0.eu-north-1.rds.amazonaws.com:3306/userDB?useSSL=false

spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
